services:
  - type: web
    name: whatsapp-job-bot
    runtime: python
    rootDirectory: whatsapp-job-bot/cv_uploads  
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app
    